### ISSUE TITLE
basic_alert gives error.

### ISSUE THREAD

**Issue by hozgur** [aitsis/uix-components#15]
@semiharslanait

**Comment by hozgur** [comment]
main.js:80  Uncaught (in promise) TypeError: Cannot set properties of null (setting 'innerHTML')
    at handleDynamicEvents (main.js:80:43)
    at a.<anonymous> (main.js:114:20)
    at I.emit (socket.io.min.js:6:7324)
    at a.value (socket.io.min.js:6:38795)
    at a.value (socket.io.min.js:6:38499)
    at a.value (socket.io.min.js:6:38153)
    at I.emit (socket.io.min.js:6:7324)
    at socket.io.min.js:6:45242
handleDynamicEvents @ main.js:80
(anonymous) @ main.js:114
I.emit @ socket.io.min.js:6
value @ socket.io.min.js:6
value @ socket.io.min.js:6
value @ socket.io.min.js:6
I.emit @ socket.io.min.js:6
(anonymous) @ socket.io.min.js:6
Promise.then (async)
at @ socket.io.min.js:6
value @ socket.io.min.js:6
I.emit @ socket.io.min.js:6
value @ socket.io.min.js:6
value @ socket.io.min.js:6
I.emit @ socket.io.min.js:6
value @ socket.io.min.js:6
I.emit @ socket.io.min.js:6
value @ socket.io.min.js:6
value @ socket.io.min.js:6
ws.onmessage @ socket.io.min.js:6
main.js:53 clientEmit :  iw1 zoom-in button_click
main.js:80  Uncaught (in promise) TypeError: Cannot set properties of null (setting 'innerHTML')
    at handleDynamicEvents (main.js:80:43)
    at a.<anonymous> (main.js:114:20)
    at I.emit (socket.io.min.js:6:7324)
    at a.value (socket.io.min.js:6:38795)
    at a.value (socket.io.min.js:6:38499)
    at a.value (socket.io.min.js:6:38153)
    at I.emit (socket.io.min.js:6:7324)
    at socket.io.min.js:6:45242

**Comment by hozgur** [comment]
#19
